import { set } from "date-fns";

export const rolePrivileges = {
  admin: {
    "employees.view": true,
    "employees.add": true,
    "employees.delete": true,
    "departments.manage": true,
    "reports.view": true,
    "settings.update": true,
    "settings.privileges": true,
    "sales.view": true,
    "sales.add": true,
    "sales.update": true,
    "sales.report": true,
    "employees.edit": true,
    "packages.view": true,
    "packages.add": true,
    "packages.edit": true,
    "packages.delete": true,
    "customers.add": true,
    "customers.view": true,
    "customers.update": true,
    "customers.delete": true,
     "management.view": true,
    "management.customers-view": true,
    "management.sales-view": true,
    "visa.manage": true,
    "operations.view": true,

   
  },

  operationManager: {
   "operations.view": true,
   "packages.view": true,
   "packages.add": true,
   "packages.edit": true,
   "packages.delete": true,
   "employees.view": true,
   "employees.add": true,
   "employees.delete": false,
   "departments.manage": true,
   "reports.view": true,
   "settings.update": false,
   "sales.view": false,
    "sales.add": false,
    "sales.update": false,
    "sales.report": false,
    "settings.privileges": false,
    "employees.edit": false,
   "management.customers-view": false,
},
  salesManager: {
    "sales.view": true,
    "sales.add": true,
    "sales.update": true,
    "sales.report": true,
    "settings.privileges": false,
    "employees.edit": false,
    "customers.add": true,
    "customers.view": true,
         "management.customers-view": false,

  },
  hr: {
    "employees.view": true,
    "employees.add": true,
    "employees.delete": false,
    "departments.manage": true,
    "reports.view": true,
    "settings.update": false,

     "sales.view": false,
    "sales.add": false,
    "sales.update": false,
    "sales.report": false,
    "settings.privileges": false,
    "employees.edit": true,
         "management.customers-view": false,

  },
  employee: {
    "employees.view": true,
    "employees.add": false,
    "employees.delete": false,
    "departments.manage": false,
    "reports.view": true,
    "settings.update": false,

     "sales.view": false,
    "sales.add": false,
    "sales.update": false,
    "sales.report": false,
    "settings.privileges": false,
    "employees.edit": false,
         "management.customers-view": false,

  },
};
